Set repSteps 'Steps in an experiment' / timing, reopt, dispatch, avgDispatch / ;

Set avgDispatchSteptoRepStep(experiments,repSteps,steps,scenSet,scenarios) "Map reporting steps to steps to accomodate dispatch solves to be averaged" /
  oldWayLite.avgDispatch.dispatch.beginSeq1932.h1932
  oldWayLite.avgDispatch.dispatch.beginSeq1933.h1933
  oldWayLite.avgDispatch.dispatch.beginSeq1934.h1934
  oldWayLite.avgDispatch.dispatch.beginSeq2004.h2004
  oldWayLite.avgDispatch.dispatch.beginSeq2005.h2005
  oldWayLite.avgDispatch.dispatch.beginSeq2006.h2006
  oldWayLite.avgDispatch.dispatch.beginSeq2007.h2007 /;
